# Generated by Django 3.2.6 on 2021-09-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210901_1050'),
        ('articles', '0002_auto_20210901_1052'),
    ]

    operations = [
    ]
